### ISSUE TITLE
Online content is not updated

### ISSUE THREAD

**Issue by techtonik** [developer-portal/content#206]
https://developer.fedoraproject.org/tools/docker/docker-installation.html
fixes for this page were landed in April and they are still not online.

**Comment by pvalena** [comment]
I am sorry- I've lost track of time/date on that in hope to get some more content released, but to avail...

I'll release by Monday 26th. Please check [staging](https://developer.stg.fedoraproject.org/) for now.

**Comment by techtonik** [comment]
Why it is not tested and pushed immediately after commit?

**Comment by pvalena** [comment]
Because as of now, we have 3-stage release [proccess](https://github.com/developer-portal/website/blob/master/RELEASE.md). That involves manually checking the changes and announcing them on our ML(and possibly fedora-devel ML).

Feel free to contact me on #developer-portal @ Freenode with further questions.

**Comment by techtonik** [comment]
What is the rationale for this process?

**Comment by pvalena** [comment]
> What is the rationale for this process?

This is mostly because of the build proccess and how the released website is hosted. There is also a plan to automate this in openshift, but I do not have time for this as of now.
Please use the contact above for further communication if you're insterested in this matter, as you'll get broader audience.

**Comment by techtonik** [comment]
Lists are offline.
```
Error 503 Backend fetch failed

Backend fetch failed

Guru Meditation:

XID: 8145936

Varnish cache server
```
Is there a communication channel with lower participation entry than ML? Some web interface with OAuth/FAS login would be much better.

**Comment by pvalena** [comment]
The ML works fine AFAIK. But I guess you have to subscribe first (FAS login there). Alternatively you can use the irc channel I've mentioned. There's few of us with very limited time, so no other communication channel is needed.

**Comment by pvalena** [comment]
And the `lists.fedoraproject.org` has also feature to post mail directly from the webui([+new thread](https://lists.fedoraproject.org/archives/list/developer-portal@lists.fedoraproject.org/message/new) button).

**Comment by techtonik** [comment]
Now I see the lists. Just that I always wanted. )
