### ISSUE TITLE
Guide about QEMU, KVM and Libvirt

### ISSUE THREAD

**Issue by t0xic0der** [developer-portal/content#392]
I have been writing myself some reference documentation here and I think this information can be used by other folks at Fedora as well https://gist.github.com/t0xic0der/efa2f9acf8da3e92772dc6c69d439c22.

**Comment by pvalena** [comment]
Hello, that sounds great! Could you open a PR with all the files? We can polish it for you. You'd also get your name in the authors section of the respective pages.

**Comment by pvalena** [comment]
In case you'd like to know more about how to contribute to Fedora Developer Portal:
https://developer-portal.github.io/contributing/
Or how does it work:
https://developer-portal.github.io/doc/structure.html

**Comment by pvalena** [comment]
Would be great fit for our [Deployment section](https://developer.fedoraproject.org/deployment.html).

https://github.com/developer-portal/content/tree/master/deployment

Maybe a `Virtualization` subsection?

**Comment by t0xic0der** [comment]
Sounds good. I'm working on the draft to make it correspond a bit more towards Fedora on the gist that I linked to in the ticket body. I would be making a PR pretty soon once we're through the NEST 2021 but I might need some assistance in linking one guide into other to keep things modular.

**Comment by pvalena** [comment]
Great!

I'll be glad to help with any PR fixes - I think I can even push into your branch (with my commits), if you leave the corresponding box checked.

_ _ _ _
But really, I think there's nothing to it.

To create a page, you add the md file, with header. To order it, within the subsection, you use `order: N` ([example](
https://github.com/developer-portal/content/pull/393/files#diff-e38fe6faf6cdd40ae7261ba71026cc2a5cc78fd4a2effeaaf5834ba566b834ccR7)).

To create a link, you use the markdown syntax `[name](/this/website/path.html)`; path same as within the repository, but with `html` extension instead of `md` ([example](https://github.com/developer-portal/content/blame/master/tools/vagrant/about.md#L18)).

**Comment by t0xic0der** [comment]
> Would be great fit for our [Deployment section](https://developer.fedoraproject.org/deployment.html):
> 
> https://github.com/developer-portal/content/tree/master/deployment
> 
> Maybe a `Virtualization` subsection?

It doesn't fit very well with the deployment section. I could of course add it to the `Tools` section but I think that we'd be better off creating a separate `Virtualization` section for this documentation.What do you think?

**Comment by jackorp** [comment]
It would make sense to add it to `Tools` as there already are tools like docker and vagrant, so when I browse the website I'd expect it there.
