### ISSUE TITLE
: python django-installation.md

### ISSUE THREAD

**Issue by jgoulart5628** [developer-portal/content#452]
Trying to use  '"from django.urls import url" wich demands the installation of url package.
There is a lot of compilation errors and the final message is: error: legacy-install-failure

Ps. Fedora 36, Python 3.10

**Comment by jackorp** [comment]
Thanks for the report! Sorry for the delay.

I am not sure that there is anything we can do. I successfully launched the web app by following the Developer Portal steps on Fedora 36.

As the guide does not specify code or any imports (just default-generated projects), the problem is probably some incompatibility that is specific to your Django app.
